version: "1.0"
info:
  model: int-scaffold
packages:
- name: ICUI_AutomaionProject1102Project
  gitServerName: ICAccount1102
  gitUrl: https://github.com/MeghaRaj69/ICUI_AutomaionProject1102Project
  gitUsername: MeghaRaj69
  gitBranch: main
